Improve verbosity of workflow test failure

diff --git a/.github/workflows/cypress-matrix-test.yml b/.github/workflows/cypress-matrix-test.yml
--- a/.github/workflows/cypress-matrix-test.yml
+++ b/.github/workflows/cypress-matrix-test.yml
@@ -53,6 +53,8 @@ jobs:
     runs-on: ubuntu-latest
     needs: test
     steps:
+      - name: Print Matrix Test Result
+        run: echo ${{ needs.test.result }}
       - name: Verify Matrix Test Result
         if: ${{ needs.test.result != 'success' }}
-        run: exit 1
+        run: echo "Tests failed!" && exit 1
